use_frameworks!

platform :ios, '13.0'

target 'TigerTradingSDK_Example' do
  pod 'TigerTradingSDK', :path => '../'
#  pod 'TigerTradingSDK', :git => 'https://github.com/tigerfintech/TigerTradingSDK.git', :branch => 'dev'

  target 'TigerTradingSDK_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
