source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/tigerfintech/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'TigerTradingSDK_Example' do
  pod 'TigerTradingSDK'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
