source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/tigerfintech/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'TigerTradingSDK_Example' do
  pod 'TigerTradingSDK'
  pod 'YYText', :git => 'https://github.com/tigerfintech/YYText.git'
  pod 'RecaptchaEnterprise', '18.7.0'
  pod 'Intercom', :git => 'https://github.com/tigerfintech/intercom-ios.git', :tag => '9.3.5.2'
  pod 'GTCaptcha4', :git => 'https://github.com/tigerfintech/GTCaptcha4.git', :tag => '1.8.8'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
