// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assetAndPositionSnapshot.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AssetSnapshot;
@class ComplexPositionSnapshot;
@class DelayQuoteSnapshot;
@class PositionSnapshot;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AssetAndPositionSnapshotRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AssetAndPositionSnapshotRoot : GPBRootObject
@end

#pragma mark - AssetAndPositionSnapshot

typedef GPB_ENUM(AssetAndPositionSnapshot_FieldNumber) {
  AssetAndPositionSnapshot_FieldNumber_AccountId = 1,
  AssetAndPositionSnapshot_FieldNumber_SegType = 2,
  AssetAndPositionSnapshot_FieldNumber_AssetSnapshot = 3,
  AssetAndPositionSnapshot_FieldNumber_PositionSnapshotArray = 4,
  AssetAndPositionSnapshot_FieldNumber_Timestamp = 5,
  AssetAndPositionSnapshot_FieldNumber_DelayQuoteSnapshotArray = 6,
  AssetAndPositionSnapshot_FieldNumber_ComplexPositionSnapshotArray = 7,
  AssetAndPositionSnapshot_FieldNumber_PortfolioId = 8,
};

/**
 * 交易长链接推送,参考: https://wiki.tigerbrokers.net/pages/viewpage.action?pageId=91914370
 **/
GPB_FINAL @interface AssetAndPositionSnapshot : GPBMessage

@property(nonatomic, readwrite) int64_t accountId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *segType;

@property(nonatomic, readwrite, strong, null_resettable) AssetSnapshot *assetSnapshot;
/** Test to see if @c assetSnapshot has been set. */
@property(nonatomic, readwrite) BOOL hasAssetSnapshot;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PositionSnapshot*> *positionSnapshotArray;
/** The number of items in @c positionSnapshotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger positionSnapshotArray_Count;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DelayQuoteSnapshot*> *delayQuoteSnapshotArray;
/** The number of items in @c delayQuoteSnapshotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger delayQuoteSnapshotArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ComplexPositionSnapshot*> *complexPositionSnapshotArray;
/** The number of items in @c complexPositionSnapshotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger complexPositionSnapshotArray_Count;

@property(nonatomic, readwrite) int64_t portfolioId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
