// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FuturesDepth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBInt64Value;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FuturesDepthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface FuturesDepthRoot : GPBRootObject
@end

#pragma mark - FuturesDepth

typedef GPB_ENUM(FuturesDepth_FieldNumber) {
  FuturesDepth_FieldNumber_Symbol = 1,
  FuturesDepth_FieldNumber_Type = 2,
  FuturesDepth_FieldNumber_Timestamp = 3,
  FuturesDepth_FieldNumber_BidDepthPriceBase = 4,
  FuturesDepth_FieldNumber_BidDepthPriceArray = 5,
  FuturesDepth_FieldNumber_BidDepthSizeArray = 6,
  FuturesDepth_FieldNumber_AskDepthPriceBase = 7,
  FuturesDepth_FieldNumber_AskDepthPriceArray = 8,
  FuturesDepth_FieldNumber_AskDepthSizeArray = 9,
  FuturesDepth_FieldNumber_Offset = 10,
};

GPB_FINAL @interface FuturesDepth : GPBMessage

/**
 * 原始JSON格式：
 * {
 *  "symbol":"GC2004",
 *  "type":"quote-fut-lv2",
 *  "timestamp":1583396042820
 *  // null表示该档位没有数据
 *  "askDepth":"[[16391,16392,16393,16394,16395,16396,16397,16398,16399,null],[16,16,14,16,16,19,9,30,22,null]]",
 *  "bidDepth":"[[16390,16389,16388,16387,16386,16385,16384,16383,null,null],[2,16,16,12,22,25,14,15,null,null]]",
 *  "offset":1
 * }
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Value *bidDepthPriceBase;
/** Test to see if @c bidDepthPriceBase has been set. */
@property(nonatomic, readwrite) BOOL hasBidDepthPriceBase;

/**
 * bidDepthPrice存储的是相对于bidDepthPriceBase的偏移量
 * 恢复为原始价格信息 price = (bidDepthPriceBase + bidDepthPrice) / 10^offset
 * 不定长，null省略
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *bidDepthPriceArray;
/** The number of items in @c bidDepthPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidDepthSizeArray;
/** The number of items in @c bidDepthSizeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthSizeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Value *askDepthPriceBase;
/** Test to see if @c askDepthPriceBase has been set. */
@property(nonatomic, readwrite) BOOL hasAskDepthPriceBase;

/**
 * askDepthPrice存储的是相对于askDepthPriceBase的偏移量
 * 恢复为原始价格信息 price = (askDepthPriceBase + askDepthPrice) / 10^offset
 * 不定长，null省略
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *askDepthPriceArray;
/** The number of items in @c askDepthPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthSizeArray;
/** The number of items in @c askDepthSizeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthSizeArray_Count;

@property(nonatomic, readwrite) int32_t offset;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
