// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HkGrey.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBInt64Value;
@class GPBStringValue;
@class HkGrey_MinuteBar;
@class HkGrey_OffsetDecimal;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HkGreyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface HkGreyRoot : GPBRootObject
@end

#pragma mark - HkGrey

typedef GPB_ENUM(HkGrey_FieldNumber) {
  HkGrey_FieldNumber_Symbol = 1,
  HkGrey_FieldNumber_Type = 2,
  HkGrey_FieldNumber_Timestamp = 3,
  HkGrey_FieldNumber_LatestPrice = 4,
  HkGrey_FieldNumber_LatestTime = 5,
  HkGrey_FieldNumber_PreClose = 6,
  HkGrey_FieldNumber_Volume = 7,
  HkGrey_FieldNumber_Amount = 8,
  HkGrey_FieldNumber_Open = 9,
  HkGrey_FieldNumber_High = 10,
  HkGrey_FieldNumber_Low = 11,
  HkGrey_FieldNumber_MarketStatus = 12,
  HkGrey_FieldNumber_MinuteBar = 13,
  HkGrey_FieldNumber_BidDepthPriceBase = 14,
  HkGrey_FieldNumber_BidDepthPriceArray = 15,
  HkGrey_FieldNumber_BidDepthVolumeArray = 16,
  HkGrey_FieldNumber_BidDepthCountArray = 17,
  HkGrey_FieldNumber_AskDepthPriceBase = 18,
  HkGrey_FieldNumber_AskDepthPriceArray = 19,
  HkGrey_FieldNumber_AskDepthVolumeArray = 20,
  HkGrey_FieldNumber_AskDepthCountArray = 21,
  HkGrey_FieldNumber_Offset = 22,
};

GPB_FINAL @interface HkGrey : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *latestPrice;
/** Test to see if @c latestPrice has been set. */
@property(nonatomic, readwrite) BOOL hasLatestPrice;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *latestTime;
/** Test to see if @c latestTime has been set. */
@property(nonatomic, readwrite) BOOL hasLatestTime;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *preClose;
/** Test to see if @c preClose has been set. */
@property(nonatomic, readwrite) BOOL hasPreClose;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *volume;
/** Test to see if @c volume has been set. */
@property(nonatomic, readwrite) BOOL hasVolume;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *amount;
/** Test to see if @c amount has been set. */
@property(nonatomic, readwrite) BOOL hasAmount;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *open;
/** Test to see if @c open has been set. */
@property(nonatomic, readwrite) BOOL hasOpen;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *high;
/** Test to see if @c high has been set. */
@property(nonatomic, readwrite) BOOL hasHigh;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *low;
/** Test to see if @c low has been set. */
@property(nonatomic, readwrite) BOOL hasLow;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *marketStatus;
/** Test to see if @c marketStatus has been set. */
@property(nonatomic, readwrite) BOOL hasMarketStatus;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_MinuteBar *minuteBar;
/** Test to see if @c minuteBar has been set. */
@property(nonatomic, readwrite) BOOL hasMinuteBar;

/** 参考 QuoteDepth.proto */
@property(nonatomic, readwrite) int64_t bidDepthPriceBase;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *bidDepthPriceArray;
/** The number of items in @c bidDepthPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidDepthVolumeArray;
/** The number of items in @c bidDepthVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidDepthCountArray;
/** The number of items in @c bidDepthCountArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthCountArray_Count;

@property(nonatomic, readwrite) int64_t askDepthPriceBase;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *askDepthPriceArray;
/** The number of items in @c askDepthPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthVolumeArray;
/** The number of items in @c askDepthVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthCountArray;
/** The number of items in @c askDepthCountArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthCountArray_Count;

@property(nonatomic, readwrite) int32_t offset;

@end

#pragma mark - HkGrey_MinuteBar

typedef GPB_ENUM(HkGrey_MinuteBar_FieldNumber) {
  HkGrey_MinuteBar_FieldNumber_Volume = 1,
  HkGrey_MinuteBar_FieldNumber_Timestamp = 2,
  HkGrey_MinuteBar_FieldNumber_AvgPrice = 3,
  HkGrey_MinuteBar_FieldNumber_Price = 4,
  HkGrey_MinuteBar_FieldNumber_High = 5,
  HkGrey_MinuteBar_FieldNumber_Low = 6,
};

GPB_FINAL @interface HkGrey_MinuteBar : GPBMessage

/** 成交量 */
@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *volume;
/** Test to see if @c volume has been set. */
@property(nonatomic, readwrite) BOOL hasVolume;

/** 分时时间戳 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Value *timestamp;
/** Test to see if @c timestamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimestamp;

/** 均价 */
@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *avgPrice;
/** Test to see if @c avgPrice has been set. */
@property(nonatomic, readwrite) BOOL hasAvgPrice;

/** 最新价 */
@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *price;
/** Test to see if @c price has been set. */
@property(nonatomic, readwrite) BOOL hasPrice;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *high;
/** Test to see if @c high has been set. */
@property(nonatomic, readwrite) BOOL hasHigh;

@property(nonatomic, readwrite, strong, null_resettable) HkGrey_OffsetDecimal *low;
/** Test to see if @c low has been set. */
@property(nonatomic, readwrite) BOOL hasLow;

@end

#pragma mark - HkGrey_OffsetDecimal

typedef GPB_ENUM(HkGrey_OffsetDecimal_FieldNumber) {
  HkGrey_OffsetDecimal_FieldNumber_LongVal = 1,
  HkGrey_OffsetDecimal_FieldNumber_Offset = 2,
};

GPB_FINAL @interface HkGrey_OffsetDecimal : GPBMessage

@property(nonatomic, readwrite) int64_t longVal;

@property(nonatomic, readwrite) int32_t offset;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
