// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HkQuoteBroker.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class HkQuoteBroker_Brokers;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HkQuoteBrokerRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface HkQuoteBrokerRoot : GPBRootObject
@end

#pragma mark - HkQuoteBroker

typedef GPB_ENUM(HkQuoteBroker_FieldNumber) {
  HkQuoteBroker_FieldNumber_Symbol = 1,
  HkQuoteBroker_FieldNumber_Type = 2,
  HkQuoteBroker_FieldNumber_Timestamp = 3,
  HkQuoteBroker_FieldNumber_AskBrokersArray = 4,
  HkQuoteBroker_FieldNumber_BidBrokersArray = 5,
  HkQuoteBroker_FieldNumber_BrokerNamesArray = 6,
  HkQuoteBroker_FieldNumber_BrokerIdsArray = 7,
  HkQuoteBroker_FieldNumber_CompactBrokerIdsArray = 8,
};

GPB_FINAL @interface HkQuoteBroker : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int64_t timestamp;

/** 卖盘经纪商列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HkQuoteBroker_Brokers*> *askBrokersArray;
/** The number of items in @c askBrokersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askBrokersArray_Count;

/** 买盘经纪商列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HkQuoteBroker_Brokers*> *bidBrokersArray;
/** The number of items in @c bidBrokersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidBrokersArray_Count;

/** 经纪商名称 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *brokerNamesArray;
/** The number of items in @c brokerNamesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger brokerNamesArray_Count;

/** 经纪商编号 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *brokerIdsArray;
/** The number of items in @c brokerIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger brokerIdsArray_Count;

/** 经纪商编号（紧密格式） */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *compactBrokerIdsArray;
/** The number of items in @c compactBrokerIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger compactBrokerIdsArray_Count;

@end

#pragma mark - HkQuoteBroker_Brokers

typedef GPB_ENUM(HkQuoteBroker_Brokers_FieldNumber) {
  HkQuoteBroker_Brokers_FieldNumber_Level = 1,
  HkQuoteBroker_Brokers_FieldNumber_Price = 2,
  HkQuoteBroker_Brokers_FieldNumber_IndicesArray = 3,
};

GPB_FINAL @interface HkQuoteBroker_Brokers : GPBMessage

/** 经纪商档位 */
@property(nonatomic, readwrite) int32_t level;

/** 档位对应价格 */
@property(nonatomic, readwrite) float price;

/** 经纪商信息索引（指向 brokerIds 与 brokerNames 数组） */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *indicesArray;
/** The number of items in @c indicesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger indicesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
