// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AuthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AuthRoot : GPBRootObject
@end

#pragma mark - DeviceSwitch

typedef GPB_ENUM(DeviceSwitch_FieldNumber) {
  DeviceSwitch_FieldNumber_Master = 1,
};

GPB_FINAL @interface DeviceSwitch : GPBMessage

/** 主设备id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *master;

@end

#pragma mark - DeviceSignin

typedef GPB_ENUM(DeviceSignin_FieldNumber) {
  DeviceSignin_FieldNumber_SigninDeviceId = 1,
  DeviceSignin_FieldNumber_SigninDevice = 2,
  DeviceSignin_FieldNumber_SigninAt = 3,
};

GPB_FINAL @interface DeviceSignin : GPBMessage

/** 登录设备id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *signinDeviceId;

/** 登录设备名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *signinDevice;

/** timestamp，单位秒 */
@property(nonatomic, readwrite) int64_t signinAt;

@end

#pragma mark - QuotePermissionPreemption

typedef GPB_ENUM(QuotePermissionPreemption_FieldNumber) {
  QuotePermissionPreemption_FieldNumber_MasterDeviceId = 1,
};

GPB_FINAL @interface QuotePermissionPreemption : GPBMessage

/** 主设备 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *masterDeviceId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
