// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CommonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface CommonRoot : GPBRootObject
@end

#pragma mark - ApiResultPB

typedef GPB_ENUM(ApiResultPB_FieldNumber) {
  ApiResultPB_FieldNumber_Ret = 1,
  ApiResultPB_FieldNumber_Msg = 2,
  ApiResultPB_FieldNumber_ServerTime = 3,
  ApiResultPB_FieldNumber_Data_p = 4,
};

GPB_FINAL @interface ApiResultPB : GPBMessage

@property(nonatomic, readwrite) int32_t ret;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite) int64_t serverTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBAny *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - LongArrayPB

typedef GPB_ENUM(LongArrayPB_FieldNumber) {
  LongArrayPB_FieldNumber_ListArray = 1,
};

GPB_FINAL @interface LongArrayPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
