// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HkOptionDepth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HkOptionDepthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface HkOptionDepthRoot : GPBRootObject
@end

#pragma mark - HkOptionDepth

typedef GPB_ENUM(HkOptionDepth_FieldNumber) {
  HkOptionDepth_FieldNumber_Type = 1,
  HkOptionDepth_FieldNumber_Symbol = 2,
  HkOptionDepth_FieldNumber_Timestamp = 3,
  HkOptionDepth_FieldNumber_BidPrice = 4,
  HkOptionDepth_FieldNumber_AskPrice = 5,
  HkOptionDepth_FieldNumber_Offset = 6,
  HkOptionDepth_FieldNumber_MinTick = 7,
  HkOptionDepth_FieldNumber_BidDepthVolumeArray = 8,
  HkOptionDepth_FieldNumber_BidDepthCountArray = 9,
  HkOptionDepth_FieldNumber_AskDepthVolumeArray = 10,
  HkOptionDepth_FieldNumber_AskDepthCountArray = 11,
};

GPB_FINAL @interface HkOptionDepth : GPBMessage

/**
 * JSON 原始格式
 * {
 *    "type": "option-depth-hk",
 *    "symbol":"TCH.HK_20200828_600.00_CALL",
 *    "timestamp":1594953573515,
 *
 *    //买卖盘
 *    "askPrice":11.67,
 *    "bidPrice":11.21,
 *
 *    // 最小价格变动
 *    "minTick":"0.01",
 *
 *    // 10 档深度数据
 *    // 由 2 个等长数组构成，分别代表：volume（数量）/ count（单量）
 *    // 每个档位的价格数据省略，需要客户端根据 askPrice / bidPrice 与 minTick 自行计算
 *    "bidDepth":"[[70,115,30,46,0,0,0,0,0,0],[1,1,1,1,0,0,0,0,0,0]]",
 *    "askDepth":"[[145,0,0,0,0,48,46,0,0,0],[1,0,0,0,0,1,1,0,0,0]]"
 * }
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) int64_t bidPrice;

@property(nonatomic, readwrite) int64_t askPrice;

@property(nonatomic, readwrite) int32_t offset;

@property(nonatomic, readwrite, copy, null_resettable) NSString *minTick;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidDepthVolumeArray;
/** The number of items in @c bidDepthVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidDepthCountArray;
/** The number of items in @c bidDepthCountArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthCountArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthVolumeArray;
/** The number of items in @c askDepthVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthCountArray;
/** The number of items in @c askDepthCountArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthCountArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
