// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HkQuoteDepth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HkQuoteDepthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface HkQuoteDepthRoot : GPBRootObject
@end

#pragma mark - HkQuoteDepth

typedef GPB_ENUM(HkQuoteDepth_FieldNumber) {
  HkQuoteDepth_FieldNumber_Symbol = 1,
  HkQuoteDepth_FieldNumber_Type = 2,
  HkQuoteDepth_FieldNumber_Timestamp = 3,
  HkQuoteDepth_FieldNumber_AskPriceArray = 4,
  HkQuoteDepth_FieldNumber_AskVolumeArray = 5,
  HkQuoteDepth_FieldNumber_AskCountArray = 6,
  HkQuoteDepth_FieldNumber_BidPriceArray = 7,
  HkQuoteDepth_FieldNumber_BidVolumeArray = 8,
  HkQuoteDepth_FieldNumber_BidCountArray = 9,
};

GPB_FINAL @interface HkQuoteDepth : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *askPriceArray;
/** The number of items in @c askPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askVolumeArray;
/** The number of items in @c askVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askCountArray;
/** The number of items in @c askCountArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askCountArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *bidPriceArray;
/** The number of items in @c bidPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidVolumeArray;
/** The number of items in @c bidVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidCountArray;
/** The number of items in @c bidCountArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidCountArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
