// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OptionDepth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - OptionDepthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface OptionDepthRoot : GPBRootObject
@end

#pragma mark - OptionDepth

typedef GPB_ENUM(OptionDepth_FieldNumber) {
  OptionDepth_FieldNumber_Symbol = 1,
  OptionDepth_FieldNumber_Type = 2,
  OptionDepth_FieldNumber_Timestamp = 3,
  OptionDepth_FieldNumber_BidDepthPriceBase = 4,
  OptionDepth_FieldNumber_BestBidIndex = 5,
  OptionDepth_FieldNumber_BidDepthPriceArray = 6,
  OptionDepth_FieldNumber_BidDepthSizeArray = 7,
  OptionDepth_FieldNumber_BidDepthTimeArray = 8,
  OptionDepth_FieldNumber_AskDepthPriceBase = 9,
  OptionDepth_FieldNumber_BestAskIndex = 10,
  OptionDepth_FieldNumber_AskDepthPriceArray = 11,
  OptionDepth_FieldNumber_AskDepthSizeArray = 12,
  OptionDepth_FieldNumber_AskDepthTimeArray = 13,
  OptionDepth_FieldNumber_Offset = 14,
  OptionDepth_FieldNumber_AskBidTime = 15,
};

GPB_FINAL @interface OptionDepth : GPBMessage

/**
 * 原始JSON格式：
 *    {
 *        "symbol": "AAPL_20201218_325.0_PUT",
 *        "type": "option-depth",
 *        "timestamp": 1583332893802,
 *
 *        // 来源于 16 个数据源的 BBO 历史数据
 *        // 16 个数据源分别是：AMEX[0], BOX[1], CBOE[2], EMLD[3], EDGX[4], GEM[5], ISE[6], MCRY[7], MIAX[8], ARCA[9], MPRL[10], NSDQ[11], BX[12], C2[13], PHLX[14], BATS[15]
 *        // 为了压缩数据量，推送数据中不包含数据源名称，订阅者获取到数据后需要自行排序，优先级依次为：价格（ask 升序；bid 降序） / 数量（降序） / 时间（降序）
 *        // 注意：可能返回价格/数量为 0 的数据，表示这个数据源的报价已经失效，这类数据可以过滤掉不展示
 *        "bbo": [ 9, 10 ],
 *        "ask": "[[49.95,0.0,49.95,0.0,49.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.7,50.05],[1,0,24,0,8,0,0,0,0,35,0,119,0,0,13,2]]",
 *        "bid": "[[0.0,0.0,0.0,0.0,0.0,0.0,48.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[0,0,515,0,0,0,10,0,0,133,178,175,0,0,369,0]]",
 *        "time": "[1583332893627,0,1583332893577,0,1583332893161,0,1583332893357,0,0,1583332893802,1583332893741,1583332893741,0,1583326800135,1583332892596,1583332893735]"
 *    }
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) int64_t bidDepthPriceBase;

@property(nonatomic, readwrite) int32_t bestBidIndex;

/**
 * bidDepthPrice存储的是相对于bidDepthPriceBase的偏移量
 * 恢复为原始价格信息 price = (bidDepthPriceBase + bidDepthPrice) / 10^offset
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *bidDepthPriceArray;
/** The number of items in @c bidDepthPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidDepthSizeArray;
/** The number of items in @c bidDepthSizeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthSizeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *bidDepthTimeArray;
/** The number of items in @c bidDepthTimeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthTimeArray_Count;

@property(nonatomic, readwrite) int64_t askDepthPriceBase;

@property(nonatomic, readwrite) int32_t bestAskIndex;

/**
 * askDepthPrice存储的是相对于askDepthPriceBase的偏移量
 * 恢复为原始价格信息 price = (askDepthPriceBase + askDepthPrice) / 10^offset
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *askDepthPriceArray;
/** The number of items in @c askDepthPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthSizeArray;
/** The number of items in @c askDepthSizeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthSizeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthTimeArray;
/** The number of items in @c askDepthTimeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthTimeArray_Count;

/** 小数点偏移量 */
@property(nonatomic, readwrite) int32_t offset;

/** ask 和 bid 的时间，ask 和 bid共用一份*/
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *time;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
