// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuoteDepth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class QuoteDepth_IntArray;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - QuoteDepthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface QuoteDepthRoot : GPBRootObject
@end

#pragma mark - QuoteDepth

typedef GPB_ENUM(QuoteDepth_FieldNumber) {
  QuoteDepth_FieldNumber_Symbol = 1,
  QuoteDepth_FieldNumber_Type = 2,
  QuoteDepth_FieldNumber_Timestamp = 3,
  QuoteDepth_FieldNumber_BidDepthPriceBase = 4,
  QuoteDepth_FieldNumber_BidDepthPriceArray = 5,
  QuoteDepth_FieldNumber_BidDepthVolumeArray = 6,
  QuoteDepth_FieldNumber_BidDepthCountArray = 7,
  QuoteDepth_FieldNumber_AskDepthPriceBase = 8,
  QuoteDepth_FieldNumber_AskDepthPriceArray = 9,
  QuoteDepth_FieldNumber_AskDepthVolumeArray = 10,
  QuoteDepth_FieldNumber_AskDepthCountArray = 11,
  QuoteDepth_FieldNumber_Offset = 12,
  QuoteDepth_FieldNumber_BidDepthSubVolumeArray = 13,
  QuoteDepth_FieldNumber_AskDepthSubVolumeArray = 14,
};

GPB_FINAL @interface QuoteDepth : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) int64_t bidDepthPriceBase;

/**
 * bidDepthPrice存储的是相对于bidDepthPriceBase的偏移量
 * 恢复为原始价格信息 price = (bidDepthPriceBase + bidDepthPrice) / 10^offset
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *bidDepthPriceArray;
/** The number of items in @c bidDepthPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidDepthVolumeArray;
/** The number of items in @c bidDepthVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *bidDepthCountArray;
/** The number of items in @c bidDepthCountArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthCountArray_Count;

@property(nonatomic, readwrite) int64_t askDepthPriceBase;

/**
 * askDepthPrice存储的是相对于askDepthPriceBase的偏移量
 * 恢复为原始价格信息 price = (askDepthPriceBase + askDepthPrice) / 10^offset
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *askDepthPriceArray;
/** The number of items in @c askDepthPriceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthPriceArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthVolumeArray;
/** The number of items in @c askDepthVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *askDepthCountArray;
/** The number of items in @c askDepthCountArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthCountArray_Count;

/** 小数点偏移位数 */
@property(nonatomic, readwrite) int32_t offset;

/** 澳洲深度子订单volume */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<QuoteDepth_IntArray*> *bidDepthSubVolumeArray;
/** The number of items in @c bidDepthSubVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidDepthSubVolumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<QuoteDepth_IntArray*> *askDepthSubVolumeArray;
/** The number of items in @c askDepthSubVolumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger askDepthSubVolumeArray_Count;

@end

#pragma mark - QuoteDepth_IntArray

typedef GPB_ENUM(QuoteDepth_IntArray_FieldNumber) {
  QuoteDepth_IntArray_FieldNumber_ValArray = 1,
};

GPB_FINAL @interface QuoteDepth_IntArray : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *valArray;
/** The number of items in @c valArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger valArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
