// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuoteTick.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MergedVol;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - QuoteTickRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface QuoteTickRoot : GPBRootObject
@end

#pragma mark - QuoteTick

typedef GPB_ENUM(QuoteTick_FieldNumber) {
  QuoteTick_FieldNumber_Type = 1,
  QuoteTick_FieldNumber_Symbol = 2,
  QuoteTick_FieldNumber_Timestamp = 3,
  QuoteTick_FieldNumber_Sn = 4,
  QuoteTick_FieldNumber_TickType = 5,
  QuoteTick_FieldNumber_TickCond = 6,
  QuoteTick_FieldNumber_PriceBase = 7,
  QuoteTick_FieldNumber_PriceOffset = 8,
  QuoteTick_FieldNumber_TimeArray = 9,
  QuoteTick_FieldNumber_PriceArray = 10,
  QuoteTick_FieldNumber_VolumeArray = 11,
  QuoteTick_FieldNumber_Tag = 12,
  QuoteTick_FieldNumber_MergedVolsArray = 13,
  QuoteTick_FieldNumber_PartCodeArray = 14,
  QuoteTick_FieldNumber_SnOffset = 15,
  QuoteTick_FieldNumber_OvernightSnOffset = 16,
};

GPB_FINAL @interface QuoteTick : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite) int64_t timestamp;

/** 首个逐笔对应的序号，从盘中开始算起 */
@property(nonatomic, readwrite) int64_t sn;

/** 逐笔方向（+-* 组成的字符串） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tickType;

/** 成交条件（该值为空时表示所有成交都是正常成交） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tickCond;

@property(nonatomic, readwrite) int64_t priceBase;

@property(nonatomic, readwrite) int32_t priceOffset;

/** 压缩后的成交时间，恢复为原时间信息 time[i] = time[i] + time[i-1] */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *timeArray;
/** The number of items in @c timeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger timeArray_Count;

/** 压缩后的成交价格，恢复为原始价格信息 price[i] = (priceBase + price[i]) / 10^priceOffset */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *priceArray;
/** The number of items in @c priceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger priceArray_Count;

/** 原始的成交量 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *volumeArray;
/** The number of items in @c volumeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger volumeArray_Count;

/** 标签，方便后续功能扩展，期货没有这个字段， */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tag;

/** 期货特有字段 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MergedVol*> *mergedVolsArray;
/** The number of items in @c mergedVolsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mergedVolsArray_Count;

/** 交易所代码，一般是 a ~ z 字符 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *partCodeArray;
/** The number of items in @c partCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger partCodeArray_Count;

/** 逐笔偏移量（相对于盘前），目前仅美股，订阅tick-V2 才使用，其它市场为0 */
@property(nonatomic, readwrite) int64_t snOffset;

/**  逐笔偏移量（夜盘），目前仅美股, 恢复从盘前的完整逐笔数量 globalSn = overnightSnOffset + snOffset + sn */
@property(nonatomic, readwrite) int64_t overnightSnOffset;

@end

#pragma mark - MergedVol

typedef GPB_ENUM(MergedVol_FieldNumber) {
  MergedVol_FieldNumber_MergeTimes = 1,
  MergedVol_FieldNumber_VolArray = 2,
};

GPB_FINAL @interface MergedVol : GPBMessage

/** 原始合并次数 */
@property(nonatomic, readwrite) int32_t mergeTimes;

/** 原始合并的成交量 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *volArray;
/** The number of items in @c volArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger volArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
