// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuoteCommon.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BondDetailPB;
@class BondKlinePB;
@class BondMutiTimeLinePB;
@class BondTimeLinePB;
@class CompareStockPB;
@class EarningsPB;
@class FuturesDecimalPB;
@class GlobalBriefPB;
@class GlobalFundamentalPB;
@class GlobalThumbnailPB;
@class GreyMarketBriefPB;
@class HourTradingMinuteQuotePB;
@class KlinePointPB;
@class KlineResponsePB;
@class LongArrayPB;
@class MultiTimelinePB;
@class NextMarketStatusPB;
@class ShortInterestPB;
@class StockHourTradingPB;
@class StockQuoteDetailPB;
@class StockQuotePB;
@class TimelinePB;
@class TimelineResponsePB;
@class YearOnYearQuotesPB;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - QuoteCommonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface QuoteCommonRoot : GPBRootObject
@end

#pragma mark - StockQuotePB

typedef GPB_ENUM(StockQuotePB_FieldNumber) {
  StockQuotePB_FieldNumber_Symbol = 1,
  StockQuotePB_FieldNumber_Volume = 2,
  StockQuotePB_FieldNumber_Halted = 3,
  StockQuotePB_FieldNumber_High = 4,
  StockQuotePB_FieldNumber_Amount = 5,
  StockQuotePB_FieldNumber_PreClose = 6,
  StockQuotePB_FieldNumber_Low = 7,
  StockQuotePB_FieldNumber_AvgPrice = 8,
  StockQuotePB_FieldNumber_Count = 9,
  StockQuotePB_FieldNumber_Time = 10,
  StockQuotePB_FieldNumber_Close = 11,
  StockQuotePB_FieldNumber_Open = 12,
};

GPB_FINAL @interface StockQuotePB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite) uint64_t volume;

@property(nonatomic, readwrite) float halted;

@property(nonatomic, readwrite) double high;

@property(nonatomic, readwrite) double amount;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite) double low;

@property(nonatomic, readwrite) double avgPrice;

@property(nonatomic, readwrite) uint64_t count;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) double close;

@property(nonatomic, readwrite) double open;

@end

#pragma mark - EarningsPB

typedef GPB_ENUM(EarningsPB_FieldNumber) {
  EarningsPB_FieldNumber_Period = 1,
  EarningsPB_FieldNumber_Weight = 2,
};

GPB_FINAL @interface EarningsPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *period;

@property(nonatomic, readwrite) double weight;

@end

#pragma mark - CompareStockPB

typedef GPB_ENUM(CompareStockPB_FieldNumber) {
  CompareStockPB_FieldNumber_Symbol = 1,
  CompareStockPB_FieldNumber_Name = 2,
};

GPB_FINAL @interface CompareStockPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - YearOnYearQuotesPB

typedef GPB_ENUM(YearOnYearQuotesPB_FieldNumber) {
  YearOnYearQuotesPB_FieldNumber_Month = 1,
  YearOnYearQuotesPB_FieldNumber_RiseRate = 2,
  YearOnYearQuotesPB_FieldNumber_AvgChangeRate = 3,
};

GPB_FINAL @interface YearOnYearQuotesPB : GPBMessage

@property(nonatomic, readwrite) int32_t month;

@property(nonatomic, readwrite) double riseRate;

@property(nonatomic, readwrite) double avgChangeRate;

@end

#pragma mark - ProfilePB

typedef GPB_ENUM(ProfilePB_FieldNumber) {
  ProfilePB_FieldNumber_WebsiteURL = 1,
  ProfilePB_FieldNumber_StockEarningsArray = 2,
  ProfilePB_FieldNumber_CompareEarningsArray = 3,
  ProfilePB_FieldNumber_CompareStock = 4,
  ProfilePB_FieldNumber_Description_p = 5,
  ProfilePB_FieldNumber_YearOnYearQuotesArray = 6,
  ProfilePB_FieldNumber_Exchange = 7,
  ProfilePB_FieldNumber_Name = 8,
  ProfilePB_FieldNumber_NameEn = 9,
};

GPB_FINAL @interface ProfilePB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *websiteURL;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EarningsPB*> *stockEarningsArray;
/** The number of items in @c stockEarningsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger stockEarningsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EarningsPB*> *compareEarningsArray;
/** The number of items in @c compareEarningsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger compareEarningsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) CompareStockPB *compareStock;
/** Test to see if @c compareStock has been set. */
@property(nonatomic, readwrite) BOOL hasCompareStock;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<YearOnYearQuotesPB*> *yearOnYearQuotesArray;
/** The number of items in @c yearOnYearQuotesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger yearOnYearQuotesArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *exchange;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nameEn;

@end

#pragma mark - ShortInterestPB

typedef GPB_ENUM(ShortInterestPB_FieldNumber) {
  ShortInterestPB_FieldNumber_ShortAvgPrice = 1,
  ShortInterestPB_FieldNumber_ShortAmount = 2,
  ShortInterestPB_FieldNumber_DaysToCover = 3,
  ShortInterestPB_FieldNumber_ShortInterest = 4,
  ShortInterestPB_FieldNumber_PercentOfFloat = 5,
  ShortInterestPB_FieldNumber_SettlementDate = 6,
  ShortInterestPB_FieldNumber_AvgDailyVolume = 7,
  ShortInterestPB_FieldNumber_AvgPrice = 8,
  ShortInterestPB_FieldNumber_Close = 9,
};

GPB_FINAL @interface ShortInterestPB : GPBMessage

@property(nonatomic, readwrite) double shortAvgPrice;

@property(nonatomic, readwrite) double shortAmount;

@property(nonatomic, readwrite) double daysToCover;

@property(nonatomic, readwrite) int64_t shortInterest;

@property(nonatomic, readwrite) double percentOfFloat;

@property(nonatomic, readwrite, copy, null_resettable) NSString *settlementDate;

@property(nonatomic, readwrite) int64_t avgDailyVolume;

@property(nonatomic, readwrite) double avgPrice;

@property(nonatomic, readwrite) double close;

@end

#pragma mark - FundamentalRespPB

typedef GPB_ENUM(FundamentalRespPB_FieldNumber) {
  FundamentalRespPB_FieldNumber_Symbol = 1,
  FundamentalRespPB_FieldNumber_FloatShares = 2,
  FundamentalRespPB_FieldNumber_Roa = 3,
  FundamentalRespPB_FieldNumber_Roe = 4,
  FundamentalRespPB_FieldNumber_LyrEps = 5,
  FundamentalRespPB_FieldNumber_VolumeRatio = 6,
  FundamentalRespPB_FieldNumber_Shares = 7,
  FundamentalRespPB_FieldNumber_DividePrice = 8,
  FundamentalRespPB_FieldNumber_High = 9,
  FundamentalRespPB_FieldNumber_Amplitude = 10,
  FundamentalRespPB_FieldNumber_PreClose = 11,
  FundamentalRespPB_FieldNumber_Low = 12,
  FundamentalRespPB_FieldNumber_Week52Low = 13,
  FundamentalRespPB_FieldNumber_PbRate = 14,
  FundamentalRespPB_FieldNumber_PsRate = 15,
  FundamentalRespPB_FieldNumber_Week52High = 16,
  FundamentalRespPB_FieldNumber_InstitutionHeld = 17,
  FundamentalRespPB_FieldNumber_LatestPrice = 18,
  FundamentalRespPB_FieldNumber_Committee = 19,
  FundamentalRespPB_FieldNumber_Eps = 20,
  FundamentalRespPB_FieldNumber_DivideRate = 21,
  FundamentalRespPB_FieldNumber_Volume = 22,
  FundamentalRespPB_FieldNumber_Delay = 23,
  FundamentalRespPB_FieldNumber_TtmEps = 24,
  FundamentalRespPB_FieldNumber_Open = 25,
  FundamentalRespPB_FieldNumber_PrevYearClose = 26,
  FundamentalRespPB_FieldNumber_FiveDayClose = 27,
  FundamentalRespPB_FieldNumber_TwentyDayClose = 28,
  FundamentalRespPB_FieldNumber_EarningDate = 29,
  FundamentalRespPB_FieldNumber_EarningTime = 30,
  FundamentalRespPB_FieldNumber_TradeService = 31,
  FundamentalRespPB_FieldNumber_ExchangeMarketSize = 32,
  FundamentalRespPB_FieldNumber_ForwardEps = 33,
  FundamentalRespPB_FieldNumber_ForwardPe = 34,
};

GPB_FINAL @interface FundamentalRespPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite) int64_t floatShares;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roa;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roe;

@property(nonatomic, readwrite) double lyrEps;

@property(nonatomic, readwrite) double volumeRatio;

@property(nonatomic, readwrite) int64_t shares;

@property(nonatomic, readwrite) double dividePrice;

@property(nonatomic, readwrite) double high;

@property(nonatomic, readwrite) double amplitude;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite) double low;

@property(nonatomic, readwrite) double week52Low;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pbRate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *psRate;

@property(nonatomic, readwrite) double week52High;

@property(nonatomic, readwrite) double institutionHeld;

@property(nonatomic, readwrite) double latestPrice;

@property(nonatomic, readwrite) double committee;

@property(nonatomic, readwrite) double eps;

@property(nonatomic, readwrite) double divideRate;

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) int32_t delay;

@property(nonatomic, readwrite) double ttmEps;

@property(nonatomic, readwrite) double open;

@property(nonatomic, readwrite) double prevYearClose;

@property(nonatomic, readwrite) double fiveDayClose;

@property(nonatomic, readwrite) double twentyDayClose;

@property(nonatomic, readwrite) int64_t earningDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *earningTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tradeService;

@property(nonatomic, readwrite) int32_t exchangeMarketSize;

@property(nonatomic, readwrite) double forwardEps;

@property(nonatomic, readwrite) double forwardPe;

@end

#pragma mark - EtfDepthDetailRespPB

typedef GPB_ENUM(EtfDepthDetailRespPB_FieldNumber) {
  EtfDepthDetailRespPB_FieldNumber_AssetSize = 1,
  EtfDepthDetailRespPB_FieldNumber_SharesOutstanding = 2,
  EtfDepthDetailRespPB_FieldNumber_Aum = 3,
  EtfDepthDetailRespPB_FieldNumber_Nav = 4,
  EtfDepthDetailRespPB_FieldNumber_DiscountPremium = 5,
  EtfDepthDetailRespPB_FieldNumber_BidAskSpread = 6,
  EtfDepthDetailRespPB_FieldNumber_NumHoldings = 7,
  EtfDepthDetailRespPB_FieldNumber_DistributionFrequency = 8,
  EtfDepthDetailRespPB_FieldNumber_AvgDailyTradingVolume = 9,
  EtfDepthDetailRespPB_FieldNumber_ShortInterest = 10,
  EtfDepthDetailRespPB_FieldNumber_NetExpenses = 11,
  EtfDepthDetailRespPB_FieldNumber_OptionsAvailable = 12,
  EtfDepthDetailRespPB_FieldNumber_OptionsVolume = 13,
  EtfDepthDetailRespPB_FieldNumber_CallVolume = 14,
  EtfDepthDetailRespPB_FieldNumber_PutVolume = 15,
};

GPB_FINAL @interface EtfDepthDetailRespPB : GPBMessage

@property(nonatomic, readwrite) double assetSize;

@property(nonatomic, readwrite) double sharesOutstanding;

@property(nonatomic, readwrite) double aum;

@property(nonatomic, readwrite) double nav;

@property(nonatomic, readwrite) double discountPremium;

@property(nonatomic, readwrite) double bidAskSpread;

@property(nonatomic, readwrite) double numHoldings;

@property(nonatomic, readwrite, copy, null_resettable) NSString *distributionFrequency;

@property(nonatomic, readwrite) double avgDailyTradingVolume;

@property(nonatomic, readwrite) double shortInterest;

@property(nonatomic, readwrite) double netExpenses;

@property(nonatomic, readwrite) BOOL optionsAvailable;

@property(nonatomic, readwrite) double optionsVolume;

@property(nonatomic, readwrite) double callVolume;

@property(nonatomic, readwrite) double putVolume;

@end

#pragma mark - GlobalFundamentalPB

typedef GPB_ENUM(GlobalFundamentalPB_FieldNumber) {
  GlobalFundamentalPB_FieldNumber_Symbol = 1,
  GlobalFundamentalPB_FieldNumber_FloatShares = 2,
  GlobalFundamentalPB_FieldNumber_Roa = 3,
  GlobalFundamentalPB_FieldNumber_Roe = 4,
  GlobalFundamentalPB_FieldNumber_LyrEps = 5,
  GlobalFundamentalPB_FieldNumber_VolumeRatio = 6,
  GlobalFundamentalPB_FieldNumber_Shares = 7,
  GlobalFundamentalPB_FieldNumber_DividePrice = 8,
  GlobalFundamentalPB_FieldNumber_High = 9,
  GlobalFundamentalPB_FieldNumber_Amplitude = 10,
  GlobalFundamentalPB_FieldNumber_PreClose = 11,
  GlobalFundamentalPB_FieldNumber_Low = 12,
  GlobalFundamentalPB_FieldNumber_Week52Low = 13,
  GlobalFundamentalPB_FieldNumber_PbRate = 14,
  GlobalFundamentalPB_FieldNumber_PsRate = 15,
  GlobalFundamentalPB_FieldNumber_Week52High = 16,
  GlobalFundamentalPB_FieldNumber_InstitutionHeld = 17,
  GlobalFundamentalPB_FieldNumber_LatestPrice = 18,
  GlobalFundamentalPB_FieldNumber_Committee = 19,
  GlobalFundamentalPB_FieldNumber_Eps = 20,
  GlobalFundamentalPB_FieldNumber_DivideRate = 21,
  GlobalFundamentalPB_FieldNumber_Volume = 22,
  GlobalFundamentalPB_FieldNumber_Delay = 23,
  GlobalFundamentalPB_FieldNumber_TtmEps = 24,
  GlobalFundamentalPB_FieldNumber_Open = 25,
  GlobalFundamentalPB_FieldNumber_PrevYearClose = 26,
  GlobalFundamentalPB_FieldNumber_FiveDayClose = 27,
  GlobalFundamentalPB_FieldNumber_TwentyDayClose = 28,
  GlobalFundamentalPB_FieldNumber_EarningDate = 29,
  GlobalFundamentalPB_FieldNumber_EarningTime = 30,
  GlobalFundamentalPB_FieldNumber_TradeService = 31,
  GlobalFundamentalPB_FieldNumber_ExchangeMarketSize = 32,
  GlobalFundamentalPB_FieldNumber_MaxScale = 33,
  GlobalFundamentalPB_FieldNumber_WeekHigh = 34,
  GlobalFundamentalPB_FieldNumber_WeekLow = 35,
  GlobalFundamentalPB_FieldNumber_MonthHigh = 36,
  GlobalFundamentalPB_FieldNumber_MonthLow = 37,
  GlobalFundamentalPB_FieldNumber_Timestamp = 38,
  GlobalFundamentalPB_FieldNumber_NameCn = 39,
  GlobalFundamentalPB_FieldNumber_LatestTime = 40,
  GlobalFundamentalPB_FieldNumber_CouponDate = 41,
  GlobalFundamentalPB_FieldNumber_CouponRate = 42,
  GlobalFundamentalPB_FieldNumber_MaturityDate = 43,
  GlobalFundamentalPB_FieldNumber_IssuePrice = 44,
};

GPB_FINAL @interface GlobalFundamentalPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite) int64_t floatShares;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roa;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roe;

@property(nonatomic, readwrite) double lyrEps;

@property(nonatomic, readwrite) double volumeRatio;

@property(nonatomic, readwrite) int64_t shares;

@property(nonatomic, readwrite) double dividePrice;

@property(nonatomic, readwrite) double high;

@property(nonatomic, readwrite) double amplitude;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite) double low;

@property(nonatomic, readwrite) double week52Low;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pbRate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *psRate;

@property(nonatomic, readwrite) double week52High;

@property(nonatomic, readwrite) double institutionHeld;

@property(nonatomic, readwrite) double latestPrice;

@property(nonatomic, readwrite) double committee;

@property(nonatomic, readwrite) double eps;

@property(nonatomic, readwrite) double divideRate;

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) int32_t delay;

@property(nonatomic, readwrite) double ttmEps;

@property(nonatomic, readwrite) double open;

@property(nonatomic, readwrite) double prevYearClose;

@property(nonatomic, readwrite) double fiveDayClose;

@property(nonatomic, readwrite) double twentyDayClose;

@property(nonatomic, readwrite) int64_t earningDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *earningTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tradeService;

@property(nonatomic, readwrite) int32_t exchangeMarketSize;

@property(nonatomic, readwrite) int32_t maxScale;

/** Forex */
@property(nonatomic, readwrite) double weekHigh;

@property(nonatomic, readwrite) double weekLow;

@property(nonatomic, readwrite) double monthHigh;

@property(nonatomic, readwrite) double monthLow;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nameCn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *latestTime;

/** Bond */
@property(nonatomic, readwrite) int64_t couponDate;

@property(nonatomic, readwrite) double couponRate;

@property(nonatomic, readwrite) int64_t maturityDate;

@property(nonatomic, readwrite) double issuePrice;

@end

#pragma mark - GlobalFundamentalsPB

typedef GPB_ENUM(GlobalFundamentalsPB_FieldNumber) {
  GlobalFundamentalsPB_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface GlobalFundamentalsPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GlobalFundamentalPB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - StockHourTradingPB

typedef GPB_ENUM(StockHourTradingPB_FieldNumber) {
  StockHourTradingPB_FieldNumber_Tag = 1,
  StockHourTradingPB_FieldNumber_LatestPrice = 2,
  StockHourTradingPB_FieldNumber_PreClose = 3,
  StockHourTradingPB_FieldNumber_LatestTime = 4,
  StockHourTradingPB_FieldNumber_Volume = 5,
  StockHourTradingPB_FieldNumber_Amount = 6,
  StockHourTradingPB_FieldNumber_Timestamp = 7,
};

GPB_FINAL @interface StockHourTradingPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag;

@property(nonatomic, readwrite) double latestPrice;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite, copy, null_resettable) NSString *latestTime;

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) double amount;

@property(nonatomic, readwrite) int64_t timestamp;

@end

#pragma mark - StockQuoteDetailPB

typedef GPB_ENUM(StockQuoteDetailPB_FieldNumber) {
  StockQuoteDetailPB_FieldNumber_LatestPrice = 1,
  StockQuoteDetailPB_FieldNumber_Halted = 2,
  StockQuoteDetailPB_FieldNumber_Amount = 3,
  StockQuoteDetailPB_FieldNumber_Volume = 4,
  StockQuoteDetailPB_FieldNumber_Change = 5,
  StockQuoteDetailPB_FieldNumber_NameCn = 6,
  StockQuoteDetailPB_FieldNumber_TradingStatus = 7,
  StockQuoteDetailPB_FieldNumber_Market = 8,
  StockQuoteDetailPB_FieldNumber_High = 9,
  StockQuoteDetailPB_FieldNumber_Amplitude = 10,
  StockQuoteDetailPB_FieldNumber_AdjPreClose = 11,
  StockQuoteDetailPB_FieldNumber_PreClose = 12,
  StockQuoteDetailPB_FieldNumber_MarketStatusCode = 13,
  StockQuoteDetailPB_FieldNumber_Low = 14,
  StockQuoteDetailPB_FieldNumber_MarketStatus = 15,
  StockQuoteDetailPB_FieldNumber_HourTrading = 16,
  StockQuoteDetailPB_FieldNumber_Exchange = 17,
  StockQuoteDetailPB_FieldNumber_LatestTime = 18,
  StockQuoteDetailPB_FieldNumber_Open = 19,
  StockQuoteDetailPB_FieldNumber_Timestamp = 20,
  StockQuoteDetailPB_FieldNumber_SymbolType = 21,
  StockQuoteDetailPB_FieldNumber_OpenAndCloseTimeListChangeArray = 22,
  StockQuoteDetailPB_FieldNumber_AskSize = 23,
  StockQuoteDetailPB_FieldNumber_BidSize = 24,
  StockQuoteDetailPB_FieldNumber_AskPrice = 25,
  StockQuoteDetailPB_FieldNumber_BidPrice = 26,
  StockQuoteDetailPB_FieldNumber_Tag = 27,
  StockQuoteDetailPB_FieldNumber_Delay = 28,
  StockQuoteDetailPB_FieldNumber_OvernightSupported = 29,
  StockQuoteDetailPB_FieldNumber_OvernightTrading = 30,
  StockQuoteDetailPB_FieldNumber_NextMarketStatus = 31,
};

GPB_FINAL @interface StockQuoteDetailPB : GPBMessage

@property(nonatomic, readwrite) double latestPrice;

@property(nonatomic, readwrite) float halted;

@property(nonatomic, readwrite) double amount;

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) double change;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nameCn;

@property(nonatomic, readwrite) int32_t tradingStatus;

@property(nonatomic, readwrite, copy, null_resettable) NSString *market;

@property(nonatomic, readwrite) double high;

@property(nonatomic, readwrite) double amplitude;

@property(nonatomic, readwrite) double adjPreClose;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite) int32_t marketStatusCode;

@property(nonatomic, readwrite) double low;

@property(nonatomic, readwrite, copy, null_resettable) NSString *marketStatus;

@property(nonatomic, readwrite, strong, null_resettable) StockHourTradingPB *hourTrading;
/** Test to see if @c hourTrading has been set. */
@property(nonatomic, readwrite) BOOL hasHourTrading;

@property(nonatomic, readwrite, copy, null_resettable) NSString *exchange;

@property(nonatomic, readwrite, copy, null_resettable) NSString *latestTime;

@property(nonatomic, readwrite) double open;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbolType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LongArrayPB*> *openAndCloseTimeListChangeArray;
/** The number of items in @c openAndCloseTimeListChangeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger openAndCloseTimeListChangeArray_Count;

@property(nonatomic, readwrite) int64_t askSize;

@property(nonatomic, readwrite) int64_t bidSize;

@property(nonatomic, readwrite) double askPrice;

@property(nonatomic, readwrite) double bidPrice;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag;

@property(nonatomic, readwrite) int32_t delay;

@property(nonatomic, readwrite) BOOL overnightSupported;

@property(nonatomic, readwrite, strong, null_resettable) StockHourTradingPB *overnightTrading;
/** Test to see if @c overnightTrading has been set. */
@property(nonatomic, readwrite) BOOL hasOvernightTrading;

@property(nonatomic, readwrite, strong, null_resettable) NextMarketStatusPB *nextMarketStatus;
/** Test to see if @c nextMarketStatus has been set. */
@property(nonatomic, readwrite) BOOL hasNextMarketStatus;

@end

#pragma mark - NextMarketStatusPB

typedef GPB_ENUM(NextMarketStatusPB_FieldNumber) {
  NextMarketStatusPB_FieldNumber_Tag = 1,
  NextMarketStatusPB_FieldNumber_TradingStatus = 2,
  NextMarketStatusPB_FieldNumber_BeginTime = 3,
};

GPB_FINAL @interface NextMarketStatusPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag;

@property(nonatomic, readwrite) int32_t tradingStatus;

@property(nonatomic, readwrite) int64_t beginTime;

@end

#pragma mark - KlinePointPB

typedef GPB_ENUM(KlinePointPB_FieldNumber) {
  KlinePointPB_FieldNumber_Volume = 1,
  KlinePointPB_FieldNumber_Amount = 2,
  KlinePointPB_FieldNumber_High = 3,
  KlinePointPB_FieldNumber_Low = 4,
  KlinePointPB_FieldNumber_Time = 5,
  KlinePointPB_FieldNumber_Close = 6,
  KlinePointPB_FieldNumber_Open = 7,
  KlinePointPB_FieldNumber_AvgPrice = 8,
  KlinePointPB_FieldNumber_Type = 9,
};

GPB_FINAL @interface KlinePointPB : GPBMessage

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) double amount;

@property(nonatomic, readwrite) double high;

@property(nonatomic, readwrite) double low;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) double close;

@property(nonatomic, readwrite) double open;

@property(nonatomic, readwrite) double avgPrice;

@property(nonatomic, readwrite) int32_t type;

@end

#pragma mark - KlineResponsePB

typedef GPB_ENUM(KlineResponsePB_FieldNumber) {
  KlineResponsePB_FieldNumber_Symbol = 1,
  KlineResponsePB_FieldNumber_Period = 2,
  KlineResponsePB_FieldNumber_Delay = 3,
  KlineResponsePB_FieldNumber_PreClose = 4,
  KlineResponsePB_FieldNumber_Detail = 5,
  KlineResponsePB_FieldNumber_ItemsArray = 6,
};

GPB_FINAL @interface KlineResponsePB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

/**
 * *
 * K线周期
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *period;

@property(nonatomic, readwrite) int32_t delay;

/**
 * *
 * 第一根K线的昨收
 * 用于计算第一根k线的涨跌幅
 **/
@property(nonatomic, readwrite) double preClose;

/** 不用全量的pb数据 */
@property(nonatomic, readwrite, strong, null_resettable) StockQuoteDetailPB *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

/**
 * *
 * K时数组
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<KlinePointPB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - KlineResponsesPB

typedef GPB_ENUM(KlineResponsesPB_FieldNumber) {
  KlineResponsesPB_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface KlineResponsesPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<KlineResponsePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - StockBriefRespPB

typedef GPB_ENUM(StockBriefRespPB_FieldNumber) {
  StockBriefRespPB_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface StockBriefRespPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<StockQuotePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - ShortInterestRespPB

typedef GPB_ENUM(ShortInterestRespPB_FieldNumber) {
  ShortInterestRespPB_FieldNumber_ItemsArray = 1,
  ShortInterestRespPB_FieldNumber_Currency = 2,
  ShortInterestRespPB_FieldNumber_UpdateDate = 3,
};

GPB_FINAL @interface ShortInterestRespPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ShortInterestPB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *currency;

@property(nonatomic, readwrite, copy, null_resettable) NSString *updateDate;

@end

#pragma mark - TimelinePB

typedef GPB_ENUM(TimelinePB_FieldNumber) {
  TimelinePB_FieldNumber_Volume = 1,
  TimelinePB_FieldNumber_Price = 2,
  TimelinePB_FieldNumber_AvgPrice = 3,
  TimelinePB_FieldNumber_Time = 4,
};

/**
 * 分时相关pb
 **/
GPB_FINAL @interface TimelinePB : GPBMessage

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) double price;

@property(nonatomic, readwrite) double avgPrice;

@property(nonatomic, readwrite) int64_t time;

@end

#pragma mark - MultiTimelinePB

typedef GPB_ENUM(MultiTimelinePB_FieldNumber) {
  MultiTimelinePB_FieldNumber_ItemsArray = 1,
  MultiTimelinePB_FieldNumber_Overnight = 2,
  MultiTimelinePB_FieldNumber_PreMarket = 3,
  MultiTimelinePB_FieldNumber_AfterHours = 4,
  MultiTimelinePB_FieldNumber_OpenAndCloseTimesArray = 5,
};

GPB_FINAL @interface MultiTimelinePB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TimelinePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *overnight;
/** Test to see if @c overnight has been set. */
@property(nonatomic, readwrite) BOOL hasOvernight;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *preMarket;
/** Test to see if @c preMarket has been set. */
@property(nonatomic, readwrite) BOOL hasPreMarket;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *afterHours;
/** Test to see if @c afterHours has been set. */
@property(nonatomic, readwrite) BOOL hasAfterHours;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LongArrayPB*> *openAndCloseTimesArray;
/** The number of items in @c openAndCloseTimesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger openAndCloseTimesArray_Count;

@end

#pragma mark - HourTradingMinuteQuotePB

typedef GPB_ENUM(HourTradingMinuteQuotePB_FieldNumber) {
  HourTradingMinuteQuotePB_FieldNumber_BeginTime = 1,
  HourTradingMinuteQuotePB_FieldNumber_EndTime = 2,
  HourTradingMinuteQuotePB_FieldNumber_ItemsArray = 3,
};

GPB_FINAL @interface HourTradingMinuteQuotePB : GPBMessage

@property(nonatomic, readwrite) int64_t beginTime;

@property(nonatomic, readwrite) int64_t endTime;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TimelinePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TimelineResponsePB

typedef GPB_ENUM(TimelineResponsePB_FieldNumber) {
  TimelineResponsePB_FieldNumber_TotalVolume = 1,
  TimelineResponsePB_FieldNumber_Symbol = 2,
  TimelineResponsePB_FieldNumber_Period = 3,
  TimelineResponsePB_FieldNumber_Delay = 4,
  TimelineResponsePB_FieldNumber_PreClose = 5,
  TimelineResponsePB_FieldNumber_Detail = 6,
  TimelineResponsePB_FieldNumber_ItemsArray = 7,
  TimelineResponsePB_FieldNumber_MultiItemsArray = 8,
  TimelineResponsePB_FieldNumber_PreMarket = 9,
  TimelineResponsePB_FieldNumber_AfterHours = 10,
  TimelineResponsePB_FieldNumber_TradingStatus = 11,
  TimelineResponsePB_FieldNumber_PreDate = 12,
  TimelineResponsePB_FieldNumber_ReqId = 13,
  TimelineResponsePB_FieldNumber_Overnight = 14,
  TimelineResponsePB_FieldNumber_OpenAndCloseTimesArray = 15,
};

GPB_FINAL @interface TimelineResponsePB : GPBMessage

@property(nonatomic, readwrite) int64_t totalVolume;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *period;

@property(nonatomic, readwrite) int32_t delay;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite, strong, null_resettable) StockQuoteDetailPB *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TimelinePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MultiTimelinePB*> *multiItemsArray;
/** The number of items in @c multiItemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger multiItemsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *preMarket;
/** Test to see if @c preMarket has been set. */
@property(nonatomic, readwrite) BOOL hasPreMarket;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *afterHours;
/** Test to see if @c afterHours has been set. */
@property(nonatomic, readwrite) BOOL hasAfterHours;

@property(nonatomic, readwrite) int64_t tradingStatus;

@property(nonatomic, readwrite) BOOL preDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reqId;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *overnight;
/** Test to see if @c overnight has been set. */
@property(nonatomic, readwrite) BOOL hasOvernight;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LongArrayPB*> *openAndCloseTimesArray;
/** The number of items in @c openAndCloseTimesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger openAndCloseTimesArray_Count;

@end

#pragma mark - TimelineMutiResponsePB

typedef GPB_ENUM(TimelineMutiResponsePB_FieldNumber) {
  TimelineMutiResponsePB_FieldNumber_TotalVolume = 1,
  TimelineMutiResponsePB_FieldNumber_Symbol = 2,
  TimelineMutiResponsePB_FieldNumber_Period = 3,
  TimelineMutiResponsePB_FieldNumber_Delay = 4,
  TimelineMutiResponsePB_FieldNumber_PreClose = 5,
  TimelineMutiResponsePB_FieldNumber_Detail = 6,
  TimelineMutiResponsePB_FieldNumber_ItemsArray = 8,
  TimelineMutiResponsePB_FieldNumber_PreMarket = 9,
  TimelineMutiResponsePB_FieldNumber_AfterHours = 10,
  TimelineMutiResponsePB_FieldNumber_TradingStatus = 11,
  TimelineMutiResponsePB_FieldNumber_PreDate = 12,
  TimelineMutiResponsePB_FieldNumber_ReqId = 13,
  TimelineMutiResponsePB_FieldNumber_Overnight = 14,
  TimelineMutiResponsePB_FieldNumber_OpenAndCloseTimesArray = 15,
};

GPB_FINAL @interface TimelineMutiResponsePB : GPBMessage

@property(nonatomic, readwrite) int64_t totalVolume;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *period;

@property(nonatomic, readwrite) int32_t delay;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite, strong, null_resettable) StockQuoteDetailPB *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MultiTimelinePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *preMarket;
/** Test to see if @c preMarket has been set. */
@property(nonatomic, readwrite) BOOL hasPreMarket;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *afterHours;
/** Test to see if @c afterHours has been set. */
@property(nonatomic, readwrite) BOOL hasAfterHours;

@property(nonatomic, readwrite) int64_t tradingStatus;

@property(nonatomic, readwrite) BOOL preDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reqId;

@property(nonatomic, readwrite, strong, null_resettable) HourTradingMinuteQuotePB *overnight;
/** Test to see if @c overnight has been set. */
@property(nonatomic, readwrite) BOOL hasOvernight;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LongArrayPB*> *openAndCloseTimesArray;
/** The number of items in @c openAndCloseTimesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger openAndCloseTimesArray_Count;

@end

#pragma mark - TimelineResponsesPB

typedef GPB_ENUM(TimelineResponsesPB_FieldNumber) {
  TimelineResponsesPB_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TimelineResponsesPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TimelineResponsePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - HistoryTimelineRespPB

typedef GPB_ENUM(HistoryTimelineRespPB_FieldNumber) {
  HistoryTimelineRespPB_FieldNumber_Volume = 1,
  HistoryTimelineRespPB_FieldNumber_High = 2,
  HistoryTimelineRespPB_FieldNumber_PreClose = 3,
  HistoryTimelineRespPB_FieldNumber_Low = 4,
  HistoryTimelineRespPB_FieldNumber_Close = 5,
  HistoryTimelineRespPB_FieldNumber_Open = 6,
  HistoryTimelineRespPB_FieldNumber_TradeDate = 7,
  HistoryTimelineRespPB_FieldNumber_ItemsArray = 8,
};

/**
 * 历史分时
 **/
GPB_FINAL @interface HistoryTimelineRespPB : GPBMessage

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) double high;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite) double low;

@property(nonatomic, readwrite) double close;

@property(nonatomic, readwrite) double open;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tradeDate;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TimelinePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - GlobalThumbnailPB

typedef GPB_ENUM(GlobalThumbnailPB_FieldNumber) {
  GlobalThumbnailPB_FieldNumber_Market = 1,
  GlobalThumbnailPB_FieldNumber_Symbol = 2,
  GlobalThumbnailPB_FieldNumber_LatestPrice = 3,
  GlobalThumbnailPB_FieldNumber_Total = 4,
  GlobalThumbnailPB_FieldNumber_PreClose = 5,
  GlobalThumbnailPB_FieldNumber_PriceArray = 6,
  GlobalThumbnailPB_FieldNumber_Open = 7,
  GlobalThumbnailPB_FieldNumber_MaxScale = 8,
};

GPB_FINAL @interface GlobalThumbnailPB : GPBMessage

/**
 * *
 * 市场
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *market;

/**
 * *
 * 代码
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

/**
 * *
 * 最新价
 **/
@property(nonatomic, readwrite) double latestPrice;

/**
 * *
 * 缩略图数据大小
 **/
@property(nonatomic, readwrite) int32_t total;

/**
 * *
 * 昨收
 **/
@property(nonatomic, readwrite) double preClose;

/**
 * *
 * 分时数组
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBDoubleArray *priceArray;
/** The number of items in @c priceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger priceArray_Count;

/**
 * *
 * 开盘价
 **/
@property(nonatomic, readwrite) double open;

/**
 * *
 * 精度，保留几位小数的意思（债券、外汇等业务才有）
 **/
@property(nonatomic, readwrite) int32_t maxScale;

@end

#pragma mark - GlobalThumbnailsPB

typedef GPB_ENUM(GlobalThumbnailsPB_FieldNumber) {
  GlobalThumbnailsPB_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface GlobalThumbnailsPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GlobalThumbnailPB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - BondDetailPB

typedef GPB_ENUM(BondDetailPB_FieldNumber) {
  BondDetailPB_FieldNumber_Symbol = 1,
  BondDetailPB_FieldNumber_SecType = 2,
  BondDetailPB_FieldNumber_Market = 3,
  BondDetailPB_FieldNumber_BondType = 4,
  BondDetailPB_FieldNumber_BondTypeName = 5,
  BondDetailPB_FieldNumber_SubType = 6,
  BondDetailPB_FieldNumber_MarketStatus = 7,
  BondDetailPB_FieldNumber_Timestamp = 8,
  BondDetailPB_FieldNumber_LatestTime = 9,
  BondDetailPB_FieldNumber_NameCn = 10,
  BondDetailPB_FieldNumber_Open = 11,
  BondDetailPB_FieldNumber_High = 12,
  BondDetailPB_FieldNumber_Low = 13,
  BondDetailPB_FieldNumber_LatestPrice = 14,
  BondDetailPB_FieldNumber_Ytm = 15,
  BondDetailPB_FieldNumber_AvgPrice = 16,
  BondDetailPB_FieldNumber_PreClose = 17,
  BondDetailPB_FieldNumber_AskPrice = 18,
  BondDetailPB_FieldNumber_BidPrice = 19,
  BondDetailPB_FieldNumber_AskYield = 20,
  BondDetailPB_FieldNumber_BidYield = 21,
  BondDetailPB_FieldNumber_Change = 22,
  BondDetailPB_FieldNumber_ChangeRate = 23,
  BondDetailPB_FieldNumber_OpenAndCloseTimesArray = 24,
  BondDetailPB_FieldNumber_CouponDate = 25,
  BondDetailPB_FieldNumber_CouponRate = 26,
  BondDetailPB_FieldNumber_MaturityDate = 27,
  BondDetailPB_FieldNumber_IssuePrice = 28,
  BondDetailPB_FieldNumber_MaxScale = 29,
  BondDetailPB_FieldNumber_CouponFrequency = 30,
  BondDetailPB_FieldNumber_RemainYears = 31,
  BondDetailPB_FieldNumber_Remains = 32,
  BondDetailPB_FieldNumber_AccruedInterest = 33,
  BondDetailPB_FieldNumber_MacDuration = 34,
  BondDetailPB_FieldNumber_ModDuration = 35,
  BondDetailPB_FieldNumber_Convexity = 36,
  BondDetailPB_FieldNumber_Issuer = 37,
  BondDetailPB_FieldNumber_ParValue = 38,
  BondDetailPB_FieldNumber_IssueSize = 39,
  BondDetailPB_FieldNumber_IssueDate = 40,
  BondDetailPB_FieldNumber_Currency = 41,
  BondDetailPB_FieldNumber_Cusip = 42,
  BondDetailPB_FieldNumber_TimeZone = 43,
  BondDetailPB_FieldNumber_Priority = 44,
  BondDetailPB_FieldNumber_Sector = 45,
  BondDetailPB_FieldNumber_RiskLocation = 46,
  BondDetailPB_FieldNumber_Redeemable = 47,
  BondDetailPB_FieldNumber_LastTradingDate = 48,
  BondDetailPB_FieldNumber_MinPurchaseAmount = 49,
  BondDetailPB_FieldNumber_RiskRating = 50,
};

GPB_FINAL @interface BondDetailPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *market;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bondType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bondTypeName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *marketStatus;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *latestTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nameCn;

@property(nonatomic, readwrite) double open;

@property(nonatomic, readwrite) double high;

@property(nonatomic, readwrite) double low;

@property(nonatomic, readwrite) double latestPrice;

@property(nonatomic, readwrite) double ytm;

@property(nonatomic, readwrite) double avgPrice;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite) double askPrice;

@property(nonatomic, readwrite) double bidPrice;

@property(nonatomic, readwrite) double askYield;

@property(nonatomic, readwrite) double bidYield;

@property(nonatomic, readwrite) double change;

@property(nonatomic, readwrite) double changeRate;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LongArrayPB*> *openAndCloseTimesArray;
/** The number of items in @c openAndCloseTimesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger openAndCloseTimesArray_Count;

@property(nonatomic, readwrite) int64_t couponDate;

@property(nonatomic, readwrite) double couponRate;

@property(nonatomic, readwrite) int64_t maturityDate;

@property(nonatomic, readwrite) double issuePrice;

@property(nonatomic, readwrite) int32_t maxScale;

@property(nonatomic, readwrite, copy, null_resettable) NSString *couponFrequency;

@property(nonatomic, readwrite) double remainYears;

@property(nonatomic, readwrite, copy, null_resettable) NSString *remains;

@property(nonatomic, readwrite) double accruedInterest;

@property(nonatomic, readwrite) double macDuration;

@property(nonatomic, readwrite) double modDuration;

@property(nonatomic, readwrite) double convexity;

@property(nonatomic, readwrite, copy, null_resettable) NSString *issuer;

@property(nonatomic, readwrite) double parValue;

@property(nonatomic, readwrite) double issueSize;

@property(nonatomic, readwrite) int64_t issueDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *currency;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cusip;

@property(nonatomic, readwrite, copy, null_resettable) NSString *timeZone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *priority;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sector;

@property(nonatomic, readwrite, copy, null_resettable) NSString *riskLocation;

@property(nonatomic, readwrite) BOOL redeemable;

@property(nonatomic, readwrite) int64_t lastTradingDate;

@property(nonatomic, readwrite) double minPurchaseAmount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *riskRating;

@end

#pragma mark - BondDetailsPB

typedef GPB_ENUM(BondDetailsPB_FieldNumber) {
  BondDetailsPB_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface BondDetailsPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BondDetailPB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - BondKlinePB

typedef GPB_ENUM(BondKlinePB_FieldNumber) {
  BondKlinePB_FieldNumber_Symbol = 1,
  BondKlinePB_FieldNumber_Time = 2,
  BondKlinePB_FieldNumber_Open = 3,
  BondKlinePB_FieldNumber_High = 4,
  BondKlinePB_FieldNumber_Low = 5,
  BondKlinePB_FieldNumber_Close = 6,
  BondKlinePB_FieldNumber_Volume = 7,
  BondKlinePB_FieldNumber_AvgPrice = 8,
  BondKlinePB_FieldNumber_Count = 9,
  BondKlinePB_FieldNumber_Amount = 10,
};

GPB_FINAL @interface BondKlinePB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) double open;

@property(nonatomic, readwrite) double high;

@property(nonatomic, readwrite) double low;

@property(nonatomic, readwrite) double close;

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) double avgPrice;

@property(nonatomic, readwrite) int64_t count;

@property(nonatomic, readwrite) double amount;

@end

#pragma mark - BondKLineRespPB

typedef GPB_ENUM(BondKLineRespPB_FieldNumber) {
  BondKLineRespPB_FieldNumber_Symbol = 1,
  BondKLineRespPB_FieldNumber_Period = 2,
  BondKLineRespPB_FieldNumber_PreClose = 3,
  BondKLineRespPB_FieldNumber_MaxScale = 4,
  BondKLineRespPB_FieldNumber_Detail = 5,
  BondKLineRespPB_FieldNumber_ItemsArray = 6,
};

GPB_FINAL @interface BondKLineRespPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *period;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite) int32_t maxScale;

@property(nonatomic, readwrite, strong, null_resettable) BondDetailPB *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BondKlinePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - BondTimeTrendRespPB

typedef GPB_ENUM(BondTimeTrendRespPB_FieldNumber) {
  BondTimeTrendRespPB_FieldNumber_Symbol = 1,
  BondTimeTrendRespPB_FieldNumber_Period = 2,
  BondTimeTrendRespPB_FieldNumber_PreClose = 3,
  BondTimeTrendRespPB_FieldNumber_MaxScale = 4,
  BondTimeTrendRespPB_FieldNumber_Detail = 5,
  BondTimeTrendRespPB_FieldNumber_ItemsArray = 6,
};

GPB_FINAL @interface BondTimeTrendRespPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *period;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite) int32_t maxScale;

@property(nonatomic, readwrite, strong, null_resettable) BondDetailPB *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BondMutiTimeLinePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - BondTimeLinePB

typedef GPB_ENUM(BondTimeLinePB_FieldNumber) {
  BondTimeLinePB_FieldNumber_Time = 1,
  BondTimeLinePB_FieldNumber_Price = 2,
  BondTimeLinePB_FieldNumber_AvgPrice = 3,
  BondTimeLinePB_FieldNumber_Volume = 4,
  BondTimeLinePB_FieldNumber_Ytm = 5,
};

GPB_FINAL @interface BondTimeLinePB : GPBMessage

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) double price;

@property(nonatomic, readwrite) double avgPrice;

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) double ytm;

@end

#pragma mark - BondMutiTimeLinePB

typedef GPB_ENUM(BondMutiTimeLinePB_FieldNumber) {
  BondMutiTimeLinePB_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface BondMutiTimeLinePB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BondTimeLinePB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - GreyMarketBriefPB

typedef GPB_ENUM(GreyMarketBriefPB_FieldNumber) {
  GreyMarketBriefPB_FieldNumber_Tag = 1,
  GreyMarketBriefPB_FieldNumber_LatestPrice = 2,
  GreyMarketBriefPB_FieldNumber_PreClose = 3,
  GreyMarketBriefPB_FieldNumber_LatestTime = 4,
  GreyMarketBriefPB_FieldNumber_Volume = 5,
  GreyMarketBriefPB_FieldNumber_Timestamp = 6,
};

GPB_FINAL @interface GreyMarketBriefPB : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *tag;

@property(nonatomic, readwrite) double latestPrice;

@property(nonatomic, readwrite) double preClose;

@property(nonatomic, readwrite, copy, null_resettable) NSString *latestTime;

@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) int64_t timestamp;

@end

#pragma mark - FuturesDecimalPB

typedef GPB_ENUM(FuturesDecimalPB_FieldNumber) {
  FuturesDecimalPB_FieldNumber_Value = 1,
  FuturesDecimalPB_FieldNumber_Offset = 2,
};

GPB_FINAL @interface FuturesDecimalPB : GPBMessage

@property(nonatomic, readwrite) int64_t value;

@property(nonatomic, readwrite) int64_t offset;

@end

#pragma mark - GlobalBriefPB

typedef GPB_ENUM(GlobalBriefPB_FieldNumber) {
  GlobalBriefPB_FieldNumber_Symbol = 1,
  GlobalBriefPB_FieldNumber_Market = 2,
  GlobalBriefPB_FieldNumber_SecType = 3,
  GlobalBriefPB_FieldNumber_NameCn = 4,
  GlobalBriefPB_FieldNumber_LatestPrice = 5,
  GlobalBriefPB_FieldNumber_Timestamp = 6,
  GlobalBriefPB_FieldNumber_PreClose = 7,
  GlobalBriefPB_FieldNumber_Halted = 8,
  GlobalBriefPB_FieldNumber_Volume = 9,
  GlobalBriefPB_FieldNumber_Auction = 10,
  GlobalBriefPB_FieldNumber_Expiry = 11,
  GlobalBriefPB_FieldNumber_HourTrading = 12,
  GlobalBriefPB_FieldNumber_GreyMarket = 13,
  GlobalBriefPB_FieldNumber_Delay = 14,
  GlobalBriefPB_FieldNumber_ChangeRate = 15,
  GlobalBriefPB_FieldNumber_Strike = 16,
  GlobalBriefPB_FieldNumber_Right = 17,
  GlobalBriefPB_FieldNumber_Name = 18,
  GlobalBriefPB_FieldNumber_FullName = 19,
  GlobalBriefPB_FieldNumber_UnderlyingSymbol = 20,
  GlobalBriefPB_FieldNumber_MaturityDate = 21,
  GlobalBriefPB_FieldNumber_Currency = 22,
  GlobalBriefPB_FieldNumber_ContractCode = 23,
  GlobalBriefPB_FieldNumber_PreSettlement = 24,
  GlobalBriefPB_FieldNumber_PriceOffset = 25,
  GlobalBriefPB_FieldNumber_DisplayMultiplier = 26,
  GlobalBriefPB_FieldNumber_MaxScale = 27,
  GlobalBriefPB_FieldNumber_FirstNoticeDate = 28,
  GlobalBriefPB_FieldNumber_LastTradingDate = 29,
  GlobalBriefPB_FieldNumber_ContractId = 30,
  GlobalBriefPB_FieldNumber_ReferMainContractCode = 31,
  GlobalBriefPB_FieldNumber_QuotesDisplayType = 32,
  GlobalBriefPB_FieldNumber_LastTradingDateTimestamp = 33,
  GlobalBriefPB_FieldNumber_CryptoVolume = 34,
};

GPB_FINAL @interface GlobalBriefPB : GPBMessage

/**
 * *
 * 标的
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

/**
 * *
 * 市场代号
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *market;

/**
 * *
 * STK 股票
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *secType;

/**
 * *
 * 中文名
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *nameCn;

/**
 * *
 * 最新价
 **/
@property(nonatomic, readwrite) double latestPrice;

/**
 * *
 * 最后交易时间
 **/
@property(nonatomic, readwrite) int64_t timestamp;

/**
 * *
 * 昨日收盘价
 **/
@property(nonatomic, readwrite) double preClose;

/**
 * *
 * 停牌（默认值为 0，保持跟原来接口一致）
 **/
@property(nonatomic, readwrite) float halted;

/**
 * *
 * 成交量（默认值为 0，保持跟原来接口一致）
 **/
@property(nonatomic, readwrite) int64_t volume;

/**
 * *
 * 是否竞价时段
 **/
@property(nonatomic, readwrite) int32_t auction;

/**
 * *
 * 到期时间
 **/
@property(nonatomic, readwrite) int64_t expiry;

/**
 * *
 * 盘前盘后交易价格
 **/
@property(nonatomic, readwrite, strong, null_resettable) StockHourTradingPB *hourTrading;
/** Test to see if @c hourTrading has been set. */
@property(nonatomic, readwrite) BOOL hasHourTrading;

/**
 * *
 * 暗盘信息
 **/
@property(nonatomic, readwrite, strong, null_resettable) GreyMarketBriefPB *greyMarket;
/** Test to see if @c greyMarket has been set. */
@property(nonatomic, readwrite) BOOL hasGreyMarket;

/**
 * *
 * 延时分钟
 **/
@property(nonatomic, readwrite) int32_t delay;

/**
 * *
 * 涨跌幅
 **/
@property(nonatomic, readwrite) double changeRate;

/**
 * *
 * 行权价(期权是 String 类型，而涡轮是 Double 类型)
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *strike;

/**
 * *
 * 看多或看空
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *right;

/** * 组合期权name 如：230630 180C/185C 1/-2 * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fullName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *underlyingSymbol;

@property(nonatomic, readwrite) int64_t maturityDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *currency;

/** * 合约代码 同symbol字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contractCode;

/** * 上个交易日的结算价格 */
@property(nonatomic, readwrite) int64_t preSettlement;

/** * 价格偏移量 */
@property(nonatomic, readwrite) int64_t priceOffset;

/** * 客户端展示行情乘数 * */
@property(nonatomic, readwrite, strong, null_resettable) FuturesDecimalPB *displayMultiplier;
/** Test to see if @c displayMultiplier has been set. */
@property(nonatomic, readwrite) BOOL hasDisplayMultiplier;

/** * 最大精度 * */
@property(nonatomic, readwrite) int32_t maxScale;

/** * 第一通知日 * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *firstNoticeDate;

/** * 最后交易日（期货是字符串，涡轮是长整形） * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastTradingDate;

/** * contractId * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contractId;

/** * 主力合约关联的合约 * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *referMainContractCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quotesDisplayType;

/** * 最后交易日(时间戳) * */
@property(nonatomic, readwrite) int64_t lastTradingDateTimestamp;

/**
 * *
 * 加密货币成交量（浮点数）
 **/
@property(nonatomic, readwrite) double cryptoVolume;

@end

#pragma mark - GlobalBriefsPB

typedef GPB_ENUM(GlobalBriefsPB_FieldNumber) {
  GlobalBriefsPB_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface GlobalBriefsPB : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GlobalBriefPB*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
