// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quote.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Quote_AskBidData;
@class Quote_MinuteBar;
@class Quote_OffsetDecimal;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - QuoteRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface QuoteRoot : GPBRootObject
@end

#pragma mark - Quote

typedef GPB_ENUM(Quote_FieldNumber) {
  Quote_FieldNumber_Type = 1,
  Quote_FieldNumber_Symbol = 2,
  Quote_FieldNumber_Timestamp = 3,
  Quote_FieldNumber_LatestPrice = 4,
  Quote_FieldNumber_LatestTime = 5,
  Quote_FieldNumber_PreClose = 6,
  Quote_FieldNumber_AskPrice = 7,
  Quote_FieldNumber_AskSize = 8,
  Quote_FieldNumber_BidPrice = 9,
  Quote_FieldNumber_BidSize = 10,
  Quote_FieldNumber_HourTradingTag = 11,
  Quote_FieldNumber_HourTradingLatestPrice = 12,
  Quote_FieldNumber_HourTradingLatestTime = 13,
  Quote_FieldNumber_HourTradingPreClose = 14,
  Quote_FieldNumber_HourTradingVolume = 15,
  Quote_FieldNumber_MinuteBar = 16,
  Quote_FieldNumber_PreSettlement = 17,
  Quote_FieldNumber_Volume = 18,
  Quote_FieldNumber_Amount = 19,
  Quote_FieldNumber_Open = 20,
  Quote_FieldNumber_Close = 21,
  Quote_FieldNumber_High = 22,
  Quote_FieldNumber_Low = 23,
  Quote_FieldNumber_MarketStatus = 24,
  Quote_FieldNumber_HtMinuteBar = 25,
  Quote_FieldNumber_HourTradingAmount = 26,
  Quote_FieldNumber_AskPartCode = 27,
  Quote_FieldNumber_BidPartCode = 28,
  Quote_FieldNumber_Ytm = 29,
  Quote_FieldNumber_AskYield = 30,
  Quote_FieldNumber_BidYield = 31,
  Quote_FieldNumber_OvernightLatestPrice = 32,
  Quote_FieldNumber_OvernightLatestTime = 33,
  Quote_FieldNumber_OvernightPreClose = 34,
  Quote_FieldNumber_OvernightVolume = 35,
  Quote_FieldNumber_OvernightAmount = 36,
  Quote_FieldNumber_OvernightMinuteBar = 37,
  Quote_FieldNumber_OvernightAskBid = 38,
};

GPB_FINAL @interface Quote : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *latestPrice;
/** Test to see if @c latestPrice has been set. */
@property(nonatomic, readwrite) BOOL hasLatestPrice;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *latestTime;
/** Test to see if @c latestTime has been set. */
@property(nonatomic, readwrite) BOOL hasLatestTime;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *preClose;
/** Test to see if @c preClose has been set. */
@property(nonatomic, readwrite) BOOL hasPreClose;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *askPrice;
/** Test to see if @c askPrice has been set. */
@property(nonatomic, readwrite) BOOL hasAskPrice;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *askSize;
/** Test to see if @c askSize has been set. */
@property(nonatomic, readwrite) BOOL hasAskSize;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *bidPrice;
/** Test to see if @c bidPrice has been set. */
@property(nonatomic, readwrite) BOOL hasBidPrice;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *bidSize;
/** Test to see if @c bidSize has been set. */
@property(nonatomic, readwrite) BOOL hasBidSize;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *hourTradingTag;
/** Test to see if @c hourTradingTag has been set. */
@property(nonatomic, readwrite) BOOL hasHourTradingTag;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *hourTradingLatestPrice;
/** Test to see if @c hourTradingLatestPrice has been set. */
@property(nonatomic, readwrite) BOOL hasHourTradingLatestPrice;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *hourTradingLatestTime;
/** Test to see if @c hourTradingLatestTime has been set. */
@property(nonatomic, readwrite) BOOL hasHourTradingLatestTime;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *hourTradingPreClose;
/** Test to see if @c hourTradingPreClose has been set. */
@property(nonatomic, readwrite) BOOL hasHourTradingPreClose;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *hourTradingVolume;
/** Test to see if @c hourTradingVolume has been set. */
@property(nonatomic, readwrite) BOOL hasHourTradingVolume;

@property(nonatomic, readwrite, strong, null_resettable) Quote_MinuteBar *minuteBar;
/** Test to see if @c minuteBar has been set. */
@property(nonatomic, readwrite) BOOL hasMinuteBar;

/** 期货昨结 */
@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *preSettlement;
/** Test to see if @c preSettlement has been set. */
@property(nonatomic, readwrite) BOOL hasPreSettlement;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *volume;
/** Test to see if @c volume has been set. */
@property(nonatomic, readwrite) BOOL hasVolume;

/** 成交额 */
@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *amount;
/** Test to see if @c amount has been set. */
@property(nonatomic, readwrite) BOOL hasAmount;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *open;
/** Test to see if @c open has been set. */
@property(nonatomic, readwrite) BOOL hasOpen;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *close;
/** Test to see if @c close has been set. */
@property(nonatomic, readwrite) BOOL hasClose;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *high;
/** Test to see if @c high has been set. */
@property(nonatomic, readwrite) BOOL hasHigh;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *low;
/** Test to see if @c low has been set. */
@property(nonatomic, readwrite) BOOL hasLow;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *marketStatus;
/** Test to see if @c marketStatus has been set. */
@property(nonatomic, readwrite) BOOL hasMarketStatus;

@property(nonatomic, readwrite, strong, null_resettable) Quote_MinuteBar *htMinuteBar;
/** Test to see if @c htMinuteBar has been set. */
@property(nonatomic, readwrite) BOOL hasHtMinuteBar;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *hourTradingAmount;
/** Test to see if @c hourTradingAmount has been set. */
@property(nonatomic, readwrite) BOOL hasHourTradingAmount;

/** 买卖盘交易所 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *askPartCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bidPartCode;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *ytm;
/** Test to see if @c ytm has been set. */
@property(nonatomic, readwrite) BOOL hasYtm;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *askYield;
/** Test to see if @c askYield has been set. */
@property(nonatomic, readwrite) BOOL hasAskYield;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *bidYield;
/** Test to see if @c bidYield has been set. */
@property(nonatomic, readwrite) BOOL hasBidYield;

/** 夜盘行情 */
@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *overnightLatestPrice;
/** Test to see if @c overnightLatestPrice has been set. */
@property(nonatomic, readwrite) BOOL hasOvernightLatestPrice;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *overnightLatestTime;
/** Test to see if @c overnightLatestTime has been set. */
@property(nonatomic, readwrite) BOOL hasOvernightLatestTime;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *overnightPreClose;
/** Test to see if @c overnightPreClose has been set. */
@property(nonatomic, readwrite) BOOL hasOvernightPreClose;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *overnightVolume;
/** Test to see if @c overnightVolume has been set. */
@property(nonatomic, readwrite) BOOL hasOvernightVolume;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *overnightAmount;
/** Test to see if @c overnightAmount has been set. */
@property(nonatomic, readwrite) BOOL hasOvernightAmount;

@property(nonatomic, readwrite, strong, null_resettable) Quote_MinuteBar *overnightMinuteBar;
/** Test to see if @c overnightMinuteBar has been set. */
@property(nonatomic, readwrite) BOOL hasOvernightMinuteBar;

@property(nonatomic, readwrite, strong, null_resettable) Quote_AskBidData *overnightAskBid;
/** Test to see if @c overnightAskBid has been set. */
@property(nonatomic, readwrite) BOOL hasOvernightAskBid;

@end

#pragma mark - Quote_MinuteBar

typedef GPB_ENUM(Quote_MinuteBar_FieldNumber) {
  Quote_MinuteBar_FieldNumber_Volume = 1,
  Quote_MinuteBar_FieldNumber_Timestamp = 2,
  Quote_MinuteBar_FieldNumber_AvgPrice = 3,
  Quote_MinuteBar_FieldNumber_Price = 4,
  Quote_MinuteBar_FieldNumber_High = 5,
  Quote_MinuteBar_FieldNumber_Low = 6,
};

GPB_FINAL @interface Quote_MinuteBar : GPBMessage

/** 成交量 */
@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *volume;
/** Test to see if @c volume has been set. */
@property(nonatomic, readwrite) BOOL hasVolume;

/** 分时时间戳 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Value *timestamp;
/** Test to see if @c timestamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimestamp;

/** 均价 */
@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *avgPrice;
/** Test to see if @c avgPrice has been set. */
@property(nonatomic, readwrite) BOOL hasAvgPrice;

/** 最新价 */
@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *price;
/** Test to see if @c price has been set. */
@property(nonatomic, readwrite) BOOL hasPrice;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *high;
/** Test to see if @c high has been set. */
@property(nonatomic, readwrite) BOOL hasHigh;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *low;
/** Test to see if @c low has been set. */
@property(nonatomic, readwrite) BOOL hasLow;

@end

#pragma mark - Quote_OffsetDecimal

typedef GPB_ENUM(Quote_OffsetDecimal_FieldNumber) {
  Quote_OffsetDecimal_FieldNumber_LongVal = 1,
  Quote_OffsetDecimal_FieldNumber_Offset = 2,
};

GPB_FINAL @interface Quote_OffsetDecimal : GPBMessage

@property(nonatomic, readwrite) int64_t longVal;

@property(nonatomic, readwrite) int32_t offset;

@end

#pragma mark - Quote_AskBidData

typedef GPB_ENUM(Quote_AskBidData_FieldNumber) {
  Quote_AskBidData_FieldNumber_AskPrice = 1,
  Quote_AskBidData_FieldNumber_AskSize = 2,
  Quote_AskBidData_FieldNumber_BidPrice = 3,
  Quote_AskBidData_FieldNumber_BidSize = 4,
  Quote_AskBidData_FieldNumber_AskPartCode = 5,
  Quote_AskBidData_FieldNumber_BidPartCode = 6,
};

GPB_FINAL @interface Quote_AskBidData : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *askPrice;
/** Test to see if @c askPrice has been set. */
@property(nonatomic, readwrite) BOOL hasAskPrice;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *askSize;
/** Test to see if @c askSize has been set. */
@property(nonatomic, readwrite) BOOL hasAskSize;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *bidPrice;
/** Test to see if @c bidPrice has been set. */
@property(nonatomic, readwrite) BOOL hasBidPrice;

@property(nonatomic, readwrite, strong, null_resettable) Quote_OffsetDecimal *bidSize;
/** Test to see if @c bidSize has been set. */
@property(nonatomic, readwrite) BOOL hasBidSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *askPartCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bidPartCode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
